sudo: false

language: node_js
node_js:
- 7

cache:
  directories:
  - node_modules
  - app/node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - icnsutils
    - graphicsmagick
    - xz-utils
    - xorriso

install:
- npm install

script:
- node --version
- npm --version
- npm run dist:linux

env:
  global:
    secure: a5AJit2jBnmvEAHLDaMOCLThn9aVtPucMLGMU+55isISKR3sEJ8mK9eg8TxLYiYtvXl3QYbv/mWRpqpnoqs+9qkugP5Z30U7Qy2ljDVhdEv0zoQNuTSCXniGI5e0YUsm7WjqwBRJL+h5i6dLEN20T308DRrI0abpqs08b6iCbR8R0v/H/r71ZSzlKZqiCB/Mn3yvA2vABlRsFqi9MC3KjwLvawDaQx9dngPxpOo7sTyfDoI8jTXX/E4fr8jUdNwvaVH+Tjqa9E+iPQ+J0l3i/wHlosZxHvpvl8O7cAWeI773dSvi/aYzLeajBMaSu52UKBO3/bwVfgKPnYxvYzCnkEKd6zLmSQm70Cf4hzUYcPwRjYRYwBdIEvTYblZwpVYcIMUGixuqruuOvFSquXXnnrCEp8RV5qbyztKtc9dJYVm8GnFZPmZfxWPln4XXDUrpHteYJgZgKTtb+WJVujxDnaQal/9tLPh04ItgrCA4BW1t1o4lPOCZS1Cm6MaRL/0n8fR6B68P2HufOaQuRI6X7olqyLAKiucOGGMOEH5p9HvbouO2K7IMD3LILse26sK+VT+2W2XMYtU5Go1GmSssZp66PbAPLeFyHzyUsnE3Ea9hMMfzzdsfhI3/T+HwjMiT41TKvFdVfHPKImZ0waZkXmWcp3is5EhMd5tzDiZglmg=
